trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - '**'
    exclude:
      - 'pipeline-templates/**'

extends:
  template: azure-pipelines-template.yml
  parameters:
    projectName: 'SocketService'
    servicePort: '8080'
    environment: 'production'
    sonarCloudOrganization: 'tu-organizacion' # Reemplaza con tu organización real
    sonarCloudProjectKey: 'tu-organizacion_SocketService' # Reemplaza con tu clave de proyecto
    additionalSteps:
      - script: |
          mvn verify -Pcoverage
        displayName: 'Socket Service'
