trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - '**'
    exclude:
      - 'pipeline-templates/**'

extends:
  template: azure-pipelines-template.yml
  parameters:
    projectName: 'SocketService'
    servicePort: '8080'
    environment: 'production'
    additionalSteps:
      - script: |
          mvn verify
        displayName: 'Socket Service'
